export const projects = [
    {
        slug: 'ipo-analyzer',
        status: 'live',
        title: 'IPO Calendar and Analyzer',
        description: "A site that tracks upcoming IPOs and uses AI to break down each filing so it's actually readable. Runs on AWS Lambda.",
        stack: ['AWS Lambda', 'Node.js', 'MongoDB'],
        liveUrl: '#',
        sourceUrl: '#',
        problem: "I wanted to keep track of upcoming IPOs but every site either buried the info or you had to read through a 100+ page filing just to understand what a company actually does.",
        build: "I set up a scheduled job on Lambda that pulls new filings automatically, then runs each one through an AI pass to summarize it in plain English instead of legal/finance jargon. Was my first time working with scheduled cloud functions instead of just building something that runs when a user clicks a button.",
    },
    {
        slug: 'options-dashboard',
        status: 'building',
        title: 'Options Analytics Dashboard',
        description: "Still building this one — a dashboard for looking at options chains without needing five different tabs open.",
        stack: ['React', 'FastAPI', 'PostgreSQL'],
        liveUrl: '#',
        sourceUrl: '#',
        problem: "Every time I wanted to look at an options chain I'd end up with a bunch of tabs open just to piece together greeks, IV, and volume. Wanted one place that shows all of it together.",
        build: "FastAPI backend pulling live chain data, React frontend doing the charting. Still working on getting the deploy set up on AWS — this is the one I'm actively building right now.",
    },
    {
        slug: 'pokemon-team-builder',
        status: 'building',
        title: 'Pokémon Team Builder',
        description: "A tool for building and testing Pokémon teams without doing the type-coverage math in your head.",
        stack: ['React', 'Node.js', 'MongoDB'],
        liveUrl: '#',
        sourceUrl: '#',
        problem: "Building a team that doesn't fall apart against common matchups usually means checking type charts across a dozen tabs. Wanted something that just tells you your team's weaknesses as you build it.",
        build: "Searchable Pokédex feeding into a team builder that runs coverage checks live as you add Pokémon. Started this one mostly to get more comfortable with MongoDB.",
    },
]